import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getDocuments } from "@/lib/documents";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DocuCraft",
  description: "Generated by create next app",
};

// layout file asynchronous করতে হবে যদি async ফাংশন (যেমন getDocuments()) কল করো
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await getDocuments(); // এখন এটা ফাংশন হিসেবে কল হয়েছে এবং async হিসেবে await করা হয়েছে

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
